from settings import *


class Config(object):
    AWS_ACCESS_KEY_ID = AWS_ACCESS_KEY_ID
    AWS_SECRET_ACCESS_KEY = AWS_SECRET_ACCESS_KEY
    S3_BUCKET = S3_BUCKET
    S3_LOCATION = S3_LOCATION
    MONGO_DBNAME = MONGO_DBNAME
    MONGO_URI = MONGO_URI
    SECRET_KEY = SECRET_KEY
    UPLOAD_FOLDER = UPLOAD_FOLDER
    username = username
    password = password
    ALLOWED_EXTENSIONS = ALLOWED_EXTENSIONS